version: 2
updates:
  # Enable version updates for npm dependencies
  - package-ecosystem: "npm"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "monday"
      time: "09:00"
    open-pull-requests-limit: 10
    reviewers:
      - "wilqq-the"
    assignees:
      - "wilqq-the"
    commit-message:
      prefix: "deps"
      prefix-development: "deps-dev"
      include: "scope"
    # Group minor and patch updates together
    groups:
      production-dependencies:
        applies-to: version-updates
        patterns:
          - "*"
        exclude-patterns:
          - "@types/*"
          - "eslint*"
          - "jest*"
          - "puppeteer*"
        update-types:
          - "minor"
          - "patch"
      development-dependencies:
        applies-to: version-updates
        patterns:
          - "@types/*"
          - "eslint*"
          - "jest*"
          - "puppeteer*"
        update-types:
          - "minor"
          - "patch"
    # Allow automatic merging of patch updates for development dependencies
    labels:
      - "dependencies"
      - "automated"
    
  # Enable version updates for GitHub Actions
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "monday"
      time: "09:00"
    open-pull-requests-limit: 5
    reviewers:
      - "wilqq-the"
    assignees:
      - "wilqq-the"
    commit-message:
      prefix: "ci"
      include: "scope"
    labels:
      - "github-actions"
      - "automated" 

